### ISSUE TITLE
How come houndci is enabled?

### ISSUE THREAD

**Issue by tkdchen** [onepiecejs/nodejs-cantas#105]
@xiaods This confused me for a while. I didn't find any configuratio to enable it. I know the way to disable it, but I have to put a YAML file in the source tree, which looks wired. Well, how is houndci enabled?

**Comment by xiaods** [comment]
Here:
https://github.com/onepiecejs/nodejs-cantas/settings/hooks

**Comment by tkdchen** [comment]
Awesome!
