### ISSUE TITLE
Be able to run with io.js as well

### ISSUE THREAD

**Issue by tkdchen** [onepiecejs/nodejs-cantas#118]
Is this necessary?

**Comment by xiaods** [comment]
not yet.

**Comment by tkdchen** [comment]
Why not

**Comment by xiaods** [comment]
socket.io is ok

**Comment by ianneilsen** [comment]
Should we look at performance or max connection scenarios of socket.io, engine.io or other websocket engines to determine which may be better at scale. I feel if max connections hit large numbers neither engine will handle and decrease user experience

**Comment by ianneilsen** [comment]
Node.js and io.js are merging their codebases. Official this year. I think we can close this proposal.http://www.infoworld.com/article/2936334/node-js/new-nodejs-merges-in-the-best-of-iojs.html

**Comment by tkdchen** [comment]
Great news. Close.
