### ISSUE TITLE
OpenShift deployment fails

### ISSUE THREAD

**Issue by EmilyDirsh** [onepiecejs/nodejs-cantas#123]
Attempting to deploy cantas to OpenShift, got through the merge step, on pushing, deployment failed with:
`Error: Cannot find module '/var/lib/openshift/5582d0f54382ec769e00002a/app-root/runtime/repo/scripts/db_init_label_metadata.js'`

It appears that the deploy hook is referencing a script that has moved and been renamed. See https://github.com/onepiecejs/nodejs-cantas/blob/master/.openshift/action_hooks/deploy#L23

**Comment by tkdchen** [comment]
Hi @EmilyDirsh fixed, please try again. BTW, after deploying successfully, you may enable the Google OAuth to login. Welcome any further feedback. Thanks.
